version: "3"

services:
  postgres:
    image: postgres:15
    container_name: blockchain-wallet-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blockchain_wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - blockchain-network

  migrate:
    image: migrate/migrate
    volumes:
      - ../migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://postgres:postgres@postgres:5432/blockchain_wallet?sslmode=disable", "up" ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - blockchain-network

  api:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: blockchain-wallet-api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blockchain_wallet
      - POSTGRES_SSLMODE=disable
      - TRON_NODE_API_KEY=2761fda4-d31e-4475-a4b7-f3ac2b86f66e
      - TRON_NODE_URL=https://api.shasta.trongrid.io
      - TRON_SCAN_API_KEY=e584273a-4a8e-45f9-a62c-ec7b03394fbb
      - TRON_SCAN_URL=https://shastapi.tronscan.org/api
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - blockchain-network

volumes:
  postgres_data:


networks:
  blockchain-network:
    driver: bridge
